### ISSUE TITLE
The plugin does not have a valid header

### ISSUE THREAD

**Issue by gellenburg** [pfefferle/wordpress-webfinger#14]
![image](https://user-images.githubusercontent.com/7026750/66256459-09447680-e75c-11e9-9f6b-4bed6178b6d8.png)

Receiving:

![image](https://user-images.githubusercontent.com/7026750/66256463-18c3bf80-e75c-11e9-80c5-35275d973505.png)

> The plugin does not have a valid header
> ```https://XXXXX/wp-admin/plugins.php?_wpnonce=27be6c5bac&action=activate&plugin=webfinger/trunk/webfinger.php```

When attempting to activate the plugin.

From the following URI:

```https://XXXXX/wp-admin/admin.php?page=ostatus-dependencies```

Yet WebFinger does look like it's getting activated:

![image](https://user-images.githubusercontent.com/7026750/66256455-e914b780-e75b-11e9-8f7e-9488c8955696.png)

**Comment by pfefferle** [comment]
Does it work when you activate it directly on the plugin page? In this case it seems to be an OStatus issue, I think.

**Comment by gellenburg** [comment]
Yes. It is active and was able to be activated from the Plugins page.

**Comment by CdRom1** [comment]
Both OStatus and Salmon have this issue.
