### ISSUE TITLE
Plugin doesn't provide any functions

### ISSUE THREAD

**Issue by regenpfeifer** [pfefferle/wordpress-webfinger#23]
It seems, that the webfinger-plugin doesn't work on my wordpress-sites. I dont't get any results if I'm trying to enter several URL's:

https://admin.regenpfeifer.net/webfinger
https://admin.regenpfeifer.net/webfinger?resource=acct:webmaster@regenpfeifer.net
https://admin.regenpfeifer.net/wp-json/webfinger
https://admin.regenpfeifer.net/wp-json/webfinger?resource=acct:webmaster@regenpfeifer.net
https://admin.regenpfeifer.net/.well-known/webfinger
https://admin.regenpfeifer.net/.well-known/webfinger?resource=acct:webmaster@regenpfeifer.net

In any case I'm getting error-messages like this one:

```
code | "rest_no_route"
message | "Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist."
data |  
status | 404

```

Are there any additional settings I have to provide in order to get sensible results?

Thank you very much!

**Comment by pfefferle** [comment]
Normally you do not have to provide any settings at all and it simply works, but depending on the setup of your host, it might be a bit tricky. It seems that the route is working but the resource parameter is not passed to that route.

**Comment by pfefferle** [comment]
This one is the correct URL: https://admin.regenpfeifer.net/.well-known/webfinger?resource=acct:webmaster@regenpfeifer.net

But as I said, it seems to load the correct endpoint but does not provide the resource param. Have you manually changed something in your htaccess and or Apache config? Where do you host your blog?

**Comment by pfefferle** [comment]
Do you use the WebFinger plugin in combination with ActivityPub?

(So many questions ☺️)

**Comment by regenpfeifer** [comment]
Thank you, Matthias!

1) I am facing this problem also on another website: https://regenpfeifer.net/.well-known/webfinger?resource=acct:webmaster@regenpfeifer.net

2) I am using the ActivityPub-plugin as well as the nodeinfo (this seems to work) and the "friends"-plugin.

3) Both sites are self-hosted on a server running Debian 11 with Apache 2.4x, PHP 8.1 and MySQL 10.5

4) The Apache VHosts have standard configuration options with some security headers set; the .htacces files are containing sections for standard WordPress, WP Super Cache and Imagify (WebP).

**Comment by pfefferle** [comment]
This site looks good https://regenpfeifer.net/.well-known/webfinger?resource=acct:webmaster@regenpfeifer.net

but the error says that there is no user with the identifier "webmaster".

**Comment by regenpfeifer** [comment]
Hm, the user "webmaster" exists...
![grafik](https://user-images.githubusercontent.com/1929807/213868698-fa4e48ee-ea2d-4658-8a01-7a6acdb49916.png)

**Comment by pfefferle** [comment]
You can find the correct identifier in the user settings of your blog.

**Comment by pfefferle** [comment]
Yes, but it is not the email address, but the username: https://regenpfeifer.net/.well-known/webfinger?resource=acct:regenpfeifer@regenpfeifer.net

As I said, you can find the correct identifier in the settings!

**Comment by pfefferle** [comment]
And for your subdomain, you have to add the subdomain also to the identifier: https://admin.regenpfeifer.net/.well-known/webfinger?resource=acct:regenpfeifer@admin.regenpfeifer.net

**Comment by pfefferle** [comment]
I can't use the mail address, because it might have a different domain, and then it wouldn't work. There is an issue, to add support for email addresses if they have the same domain, but that does not work yet.

**Comment by regenpfeifer** [comment]
Thank you very much, Matthias! When I set the query in the form USERNAME@BLOG-DOMAIN everything works fine now!  I thought that I would have to use the settings from the WordPress user-entries...
