### ISSUE TITLE
webfinger is leaking email address

### ISSUE THREAD

**Issue by shleeable** [pfefferle/wordpress-webfinger#26]
https://shlee.fedipress.au/.well-known/webfinger?resource=acct:shlee@shlee.fedipress.au

![image](https://user-images.githubusercontent.com/17537000/225483809-f1d93dfc-63b4-4758-a25e-7c21d620288f.png)

Can we remove the email? It ain't required.

**Comment by pfefferle** [comment]
Keep!

**Comment by pfefferle** [comment]
keep
