### ISSUE TITLE
How is this plugin supposed to be used?

### ISSUE THREAD

**Issue by jangxx** [pfefferle/wordpress-webfinger#29]
I installed the plugin on my server, expecting to find a settings page or something, where I can enter the respective relations to return for email addresses. Unfortunately the plugin has no settings page at all, and the instructions are not helpful to me either. 

How or where can I specify anything JRD related? Where am I supposed to put the code that the instructions mention for "extending the JRD file"? The wordpress admin backend does not have a way to just specify arbitrary code to be run as far as I'm aware.

Sorry I'm a total Wordpress noob and I'm just trying to use this plugin so that tailscale can find our Keycloak server which runs on a different domain from our company emails.

(Also I know that this isn't really an "Issue", but this project doesn't use the "Discussions" feature and I don't know where else to ask).

**Comment by pfefferle** [comment]
The plugin does not have any settings, it auto-generates the WebFinger profile from WordPress Data and is extended by other plugins. The easiest way to extend the JRD file is with a plugin.

What exactly do you plan to add to the WebFinger JRD file? Maybe this might be a feature for future versions.

**Comment by jangxx** [comment]
Thanks for the quick response! I'm trying to implement the WebFinger setup outlined here: https://tailscale.com/kb/1240/sso-custom-oidc/#webfinger-setup

Essentially I just need something that I can throw any `$name@company.com` email into and which then returns 

```
{
  "subject": "acct:$name@company.com",
  "links": [
    {
      "rel": "http://openid.net/specs/connect/1.0/issuer",
      "href": "https://auth.company.com/realms/company"
    }
  ]
}
```

Hacking this together without Wordpress sounds trivial, but since we already use Wordpress for our company website, I thought it would be easier to just use this plugin and not having to mess around with reverse-proxying the `/.well-known/webfinger` path to a custom solution. If I first have to figure out how to write a Wordpress plugin just for this one thing though, I think I'm just gonna do it without Wordpress after all.
