### ISSUE TITLE
Customize user profile info returned by plugin?

### ISSUE THREAD

**Issue by aaribaud** [pfefferle/wordpress-webfinger#31]
Hello,

I manage a multisite (subdirectories variant) install where each user of the network has a specific subsite as their primary blog (meta_key 'primary_blog' in wp_usermeta).

I would like a way to make the webfinger plugin only provide this primary blog, not the "main" site, in the user profile.

How can I do this?

If developing is involved, I *may* be able to try and provide a branch, but I would need a few pointers for where in the code to look.

**Comment by pfefferle** [comment]
https://github.com/Automattic/wordpress-activitypub/issues/414#issuecomment-1713525092
