### ISSUE TITLE
Help in using web finger

### ISSUE THREAD

**Issue by ldemattos** [pfefferle/wordpress-webfinger#33]
I am trying to use the activity pub Wordpress plugin to integrate my blog to mastodon. This plugin requested the installation of the webfinger plugin.

At the moment, I am not being able to actually connect to my blog from mastodon. On Wordpress "health status page", I have:

`Your WebFinger endpoint https://www.mattos.eng.br/.well-known/webfinger?resource=acct:leonardo@www.mattos.eng.br is not accessible. Please check your WordPress setup or permalink structure.`

I don't have any idea how to solve this. Could you please give some directions?

Thanks in advance.

**Comment by pfefferle** [comment]
Hey @ldemattos I am sorry, but WebFinger does only work with enabled SSL (https).

**Comment by ldemattos** [comment]
Hello @pfefferle, understood. Thanks for the feedback!

**Comment by ldemattos** [comment]
No need to let this issue open. I am closing it. Thanks!

**Comment by ldemattos** [comment]
No need to let this issue open. I´m closing it.

**Comment by ldemattos** [comment]
No need to let this issue open. I´m closing it.
